<?php

namespace App\Domain;

/*
Julian Welge - cscd 378 - Dr. Breshears
2/10/2021

Assignment Description:

Class named CityAnalyzer that is initialized/constructed with collection data returned from CensusAPI::fetchCities. 
This class should have methods that are responsible for:
Mapping the json collections data into PHP array of city objects
Find and print the 10 highest populated cities
Find and print the 10 lowest populated cities
Find and return a random city
returns a string (generated by the city, see Example output)
*/


use Illuminate\Support\Collection;

class CityAnalyzer
{

    public $fetchedCities;

    public function __construct()
    {
        $citiesData = CensusAPI::fetchCities();
        $this->fetchedCities = collect($citiesData)->map(function ($city) {
            return new City($city["place_name"], $city["total_population_2010"]);
        });
    }

    //returns the 10 highest populated cities (ordered high to low)
    public function topTenPopulation()
    {
        $tenCitiesPop = collect();
        $decendingCityPopFull = $this->fetchedCities->sortByDesc('population');
        $decendingCityPopFull = $decendingCityPopFull->reverse();
        for ($x = 0; $x < 10; ++$x) {
            $tenCitiesPop->push($decendingCityPopFull->pop());
        }
        return $tenCitiesPop;
    }

    // returns the 10 lowest populated cities (ordered low to high)
    public function bottomTenPopulation()
    {
        $tenCitiesPop = collect();
        $decendingCityPopFull = $this->fetchedCities->sortByDesc('population');
        for ($x = 0; $x < 10; ++$x) {
            $tenCitiesPop->push($decendingCityPopFull->pop());
        }
        return $tenCitiesPop;
    }

    //returns a randomly selected city from the collection
    public function randomCity()
    {
        return $this->fetchedCities->random(1);
    }

    //calls and prints the results of the methods above. currently: topTen, bottomTen, randomCity
    public function populationReport()
    {
        printf("\nPopulation Report for 2010\n==========================\n\nTen Highest Populated Cities\n----------------------------\n");
        foreach ($this->topTenPopulation() as $city) {
            echo $city, "\n";
        }
        printf("\nTen Lowest Populated Cities\n---------------------------\n");
        foreach ($this->bottomTenPopulation() as $city) {
            echo $city, "\n";
        }
        printf("\nRandom City: "); 
        echo $this->randomCity()->pop();
      
    }
}
